name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * 1'  # Weekly scan
permissions: read-all
jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
